apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./deployment/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: devf1d/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      # change synced files
      # inject changes to the pod
      sync:
        manual:
          # synced files
          - src: "src/**/*.ts"
            dest: .
      # change unsynced files
    - image: devf1d/client
      context: client
      docker:
        dockerfile: Dockerfile
      # change synced files
      # inject changes to the pod
      sync:
        manual:
          # synced files
          - src: "**/*.js"
            dest: .
    - image: devf1d/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      # change synced files
      # inject changes to the pod
      sync:
        manual:
          # synced files
          - src: "src/**/*.ts"
            dest: .1
    - image: devf1d/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      # change synced files
      # inject changes to the pod
      sync:
        manual:
          # synced files
          - src: "src/**/*.ts"
            dest: .
    - image: devf1d/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      # change synced files
      # inject changes to the pod
      sync:
        manual:
          # synced files
          - src: "src/**/*.ts"
            dest: .
